#!/bin/bash
torchrun --standalone --nnodes=1 --nproc_per_node=8 experiments/train_net3d_2s_deepcopy.py --sym_loss --infonce --epochs 400 --seed 233
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 400
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 400 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 300
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 300 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 200
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 200 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 100
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 100 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 10
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 10 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 20
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 20 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 30
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 30 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 40
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 40 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 50
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 50 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 60
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 60 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 70
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 70 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 80
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 80 --which_encoder 2
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 90
python evaluation/eval_retrieval.py --ckpt_folder /data/checkpoints_yehengz/2streams_deepcopy_net_and_proj/ucf1.0_nce2s_r3d18/symTrue_bs64_lr4.8_wd1e-06_ds3_sl8_nw_randFalse_seed233_operation_summation --epoch_num 90 --which_encoder 2